# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170116_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favoritess'},
        ),
    ]
