# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170116_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('track_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together=set([('user_id', 'track_id')]),
        ),
    ]
