# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170116_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='core.Track'),
        ),
    ]
