# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_track_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='platform',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
