# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favorite_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesList',
            fields=[
                ('user_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Favorites list',
                'verbose_name_plural': 'Favorites lists',
            },
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorite'},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='favoriteslist',
            name='favorites',
            field=models.ManyToManyField(to='core.Favorite'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_id',
        ),
    ]
